### ISSUE TITLE
Better way to integrate with CocoaPods

### ISSUE THREAD

**Issue by adamwulf** [adamwulf/PerformanceBezier#5]
Currently the project requires the iOS Real Framework to be installed in Xcode. This is great, b/c it builds a proper static framework, but is unfortunately because it requires an Xcode plugin.

Ideally, this would be able to build a static framework w/o the custom Xcode plugin, and would also be easier to integrate with those who use cocoa pods.

**Comment by msand** [comment]
Thanks for your great work!

What needs to be done to get cocoapods support? I need to fix support for it to https://github.com/msand/react-native-svg and currently PerformanceBezier is blocking it:

/Users/user/rntest/ios/Pods/../../node_modules/react-native-svg/ios/Text/RNSVGTSpan.h:9:9: fatal error: 'PerformanceBezier/PerformanceBezier.h' file not found
#import <PerformanceBezier/PerformanceBezier.h>

**Comment by adamwulf** [comment]
Good question - I'm honestly not sure. I'm not a cocoapods users myself, so I'm not sure the right way to build new pods. I think the trickiest part of this might be the build scripts I'm using to package it as a proper framework.

I think there's a way for cocoapods to reference a built .framework file directly, and that might be a good option - just build PerformanceBezier and then use cocoapods to link to that built version instead of building from source.

I'd love to know what you come up with!

**Comment by msand** [comment]
I have one workaround that I'm not sure if it is correct/sensible. https://github.com/msand/react-native-svg/commit/afb238d22a3d42157028c6d2500a87eb9581930c
I placed the header file in my project, and then the compiler started complaining on a few memory handling statements being incompatible with the automatic reference counting and some typecasts which were needed. Googling around suggested just removing the memory handling statements, and xcode suggested some typecasts to add. 

Haven't tested it properly, mostly just that it builds correctly and works with cocoapods, (and using faslane in circleci). Have to ensure that the memory is still handled correctly, but I'm quite new to the mac ecosystem (got access to a mac for the first time about 2 months ago) and fresh to the obj-c memory handling syntax and behavior of ARC. Would you have any insight/suggestions, a review of the commit would be most helpful <3

**Comment by adamwulf** [comment]
Importing the header file directly into your project should work fine I believe. You may need to simply import all the source files as well, as sometimes category methods aren't actually linked properly into the binary with certain flags set. If its not using the true .framework that's built, then you might be better off just putting all the source into your project's target.

For the memory errors, instead of changing from non-ARC to ARC, you can set a compiler flag for those files specifically:
<img width="666" alt="screen shot 2017-09-30 at 3 55 38 pm" src="https://user-images.githubusercontent.com/251087/31049418-208b430c-a5f8-11e7-8ecb-e6d7364f42bd.png">


Your memory fixes will probably work, but there's some tricky memory issues in this project, and it's probably safer to just use the existing memory management code.

**Comment by psivanov** [comment]
@msand, I tried to update to https://github.com/msand/react-native-svg 6.0.0 and I get:

/Users/petar.ivanov/Documents/git/mobile/zazzle-react-native/node_modules/react-native-svg/ios/PerformanceBezier/PerformanceBezierTests/PerformanceBezierAbstractTest.m:9:9: fatal error: 'XCTest/XCTest.h' file not found
#import <XCTest/XCTest.h>

**Comment by adamwulf** [comment]
Closing this out - @thaya-cameraxis has graciously published a pod, and I'll be keeping it up to date for the foreseeable future. 🎉
