### ISSUE TITLE
UIBezierPathProperties.m memory leak

### ISSUE THREAD

**Issue by danh-geo** [adamwulf/PerformanceBezier#9]
I was using Instrument to debug, and using "Leaks" it detects a memory leak in the non ARC file UIBezierPathProperties.m
lock = [[NSObject alloc] init];
Don't you need to release lock?

**Comment by adamwulf** [comment]
ah good find! This should be fixed in bee6bfb6, thanks!

**Comment by adamwulf** [comment]
Just pushed this up as 1.0.10 :)
